### ISSUE TITLE
Use non-default user-agent which identifies the library as Messente's

### ISSUE THREAD

**Issue by UkuLoskit** [messente/verigator-java#2]

**Comment by Meravici** [comment]
Any ideas what should we name our user agent?

**Comment by UkuLoskit** [comment]
https://github.com/messente/messente-python/blob/master/messente/api/api.py#L101

something similar?

**Comment by jbaanus** [comment]
Yes, it should be simplistic, stating "messente", the language (java/python) and version of the library.
Let's use the same syntax as the link which @UkuLoskit posted.

**Comment by Meravici** [comment]
So for example `messente-verigator-java-0.0.1`, `messente-hlr-python-0.0.2`?

**Comment by UkuLoskit** [comment]
yes
